---
title: "About"
---

## Name: 
Nathan Sunho Kim

## Email: 
nathankim184@gmail.com

## Education
College (Los Angeles, CA):
University of California, Los Angeles | Major in Statistics and Data Science | Minor in Accounting | GPA: 3.8

# High School (Fullerton, CA):
Sunny Hills High School | GPA: 4.8

## Experiences:
# PricewaterhouseCooper (PwC) (Irvine, CA) \n
Digital Assurance & Transparency Intern (Irvine, CA) | June 2025 - Aug 2025

# Bruin Sports Analytics (Los Angeles, CA) 
Financial Head | Sept 2024 - June 2025
Data Consultant | Sept 2023 - June 2024, Sept 2024 - June 2025

# UCLA Residential Life (Los Angeles, CA)
Residential Assistant | Aug 2024 - June 2025
Treasurer (Resident Government Council) | Sept 2023 - June 2024

# Federal Reserve of Kansas City (Kansas City, MO):
Analyst Intern | June 2024 - Aug 2024

# New Student Academic Program at UCLA (Los Angeles, CA)
New Student Adviser | March 2023 - Dec 2023

# Lifeguard (La Mirada, CA)
Lifeguard | May 2022 - Aug 2022

# United States Military Academy at West Point (West Point, New York)
Cadet | May 2021 - June 2021




